### ISSUE TITLE
Feature Request: Open Search View → I can NOT Close the Search View Tab

### ISSUE THREAD

**Issue by FelipeRearden** [Quorafind/Obsidian-Float-Search#15]
### Feature Requested

Hello @Quorafind !!!

Just to let you know that the native command that closes the Active Tab `Close Current Tab` is not available when I am in a Search View Tab.

This way, I am having a hard time to close Search Tab  using the **keyboard** :)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by daxmonson** [comment]
Also, there is no option on the tab to close it as there is with a normal note's tab. When it's opened from the command palette it isn't "floating," it opens as a note. It's also automatically pinned which is interesting. Let me know if I can help debug.

<img width="201" alt="Screenshot 2023-07-27 at 1 26 43 PM" src="https://github.com/Quorafind/Obsidian-Float-Search/assets/5855930/a25d1e6e-26b6-421b-a530-7c0332813195">

**Comment by Quorafind** [comment]
Got fixed. When you want to close the leaf, remember lose focus in inputel first. Because inputel will catch all input.
