### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lwb52** [Quorafind/Obsidian-Float-Search#17]
### Bug Description

The info panel in Obsidian shows the descriptor for this plugin as "Enhanced highlights for Obsidian”—this is exactly the same as the descriptor for the Floating Highlights plugin, and does not correctly describe your plugin's functionality…

### Relevant Screenshot

![ScreenShot- 2023-04-08 at 14 41 03 ](https://user-images.githubusercontent.com/22728371/230743744-266a9fa6-29d2-4bb1-bc09-afa5ebd1a384.png)

### Obsidian Version

1.2.2

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Should be fixed
