### ISSUE TITLE
[Bug]: can't close search 

### ISSUE THREAD

**Issue by j-r-e-i-d** [Quorafind/Obsidian-Float-Search#18]
### Bug Description

Even after uninstalling this buggy plug-in I am left with multiple search 'pages' that I cannot close.

### Relevant Screenshot

<img width="622" alt="Screen Shot 2023-04-09 at 14 15 43" src="https://user-images.githubusercontent.com/96575315/230754139-894556ae-cd00-40ff-8a0b-837eddf4da83.png">

### To Reproduce

1. Invoke search via the established hotkey
2. Weep

### Obsidian Version

1.2.2

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Press on the pin icon and then unpin it then close it. Or right click on the tab header to close them like other views.
![image](https://user-images.githubusercontent.com/13215013/230755824-a3741e2b-7ecb-4618-8737-7943e5ea40e5.png)
