### ISSUE TITLE
[Bug]: Cannot click arrow to collapse results

### ISSUE THREAD

**Issue by tim-hilde** [Quorafind/Obsidian-Float-Search#20]
### Bug Description

I can not click the arrow to collapse results 

<img width="1920" alt="image" src="https://github.com/Quorafind/Obsidian-Float-Search/assets/44113468/63645441-d1a2-4888-8d24-73b3077dbefd">

Instead the modal closes

### Relevant Screenshot

<img width="1920" alt="image" src="https://github.com/Quorafind/Obsidian-Float-Search/assets/44113468/596a6903-20cd-44fa-97ef-7bd307548fa5">

### Obsidian Version

3.3

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
supported in 3.3.1
