### ISSUE TITLE
[Bug]: cannot click to jump special note

### ISSUE THREAD

**Issue by doit132** [Quorafind/Obsidian-Float-Search#21]
### Bug Description

when I click a search result to jump special note, I find I can't

### Relevant Screenshot

![动画-tuya-tuya-tuya-tuya](https://github.com/Quorafind/Obsidian-Float-Search/assets/117004316/49c029a6-70b9-4d38-8c29-27acb07bb5e6)

### Obsidian Version

V1.3.3

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Can you try 1.3.4 and see if it is already fixed ? I found it is related to the default behavior changed by Obsidian.
