### ISSUE TITLE
Clicking an entry should open the file/entry

### ISSUE THREAD

**Issue by tim-hilde** [Quorafind/Obsidian-Float-Search#24]
### Feature Requested

Clicking an entry should open the file/entry. This should also allow using modifiers to open in a new tab etc.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Which version are you using?

**Comment by tim-hilde** [comment]
Weird, after testing it again it works. Sorry for the misunderstanding
