### ISSUE TITLE
[Bug]: After search, "Undo close tab" opens search

### ISSUE THREAD

**Issue by valteriomon** [Quorafind/Obsidian-Float-Search#26]
### Bug Description

After using the floating search, the "Undo close tab" command (ctrl+shift+t) opens the search in a tab.

### To Reproduce

1. Close tab
2. Search something
3. Reopen tab using the "Undo close tab" command
4. Search tab appears on a new pane instead of the tab from step 1

### Obsidian Version

1.3.5

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Fixed in 3.3.4
