### ISSUE TITLE
[Bug]: Open action on search results are broken when the active tab is pinned

### ISSUE THREAD

**Issue by rhcdc** [Quorafind/Obsidian-Float-Search#28]
### Bug Description

When the current active tab in obsidian is pinned, the open actions in the aroused float search panel (i.e. enter/alt+enter or with mouse) seem broken.

### To Reproduce

1. Create a new tab and pin it in obsidian;
2. Arouse the float search panel and do random search;
3. Try to open any result item:
   (a) Click on the item will shut down the float search panel but the result is not shown in background;
   (b) Choose any item and press enter will open it in the float search panel;
   (c) Choose any item and press alt+enter will lead to the very same situation seen in (a).

### Obsidian Version

1.3.5

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Should be got fixed.
