### ISSUE TITLE
[Bug]: 每次重启Obsidian后，Float-Search插件的搜索设置就会重置

### ISSUE THREAD

**Issue by wi196324** [Quorafind/Obsidian-Float-Search#29]
### Bug Description

每次重启Obsidian后，Float-Search插件的悬浮窗口的搜索设置就会重置。Obsidian自带的全局搜索设置重启软件后设置还有保留

### Relevant Screenshot

<img width="476" alt="123" src="https://github.com/Quorafind/Obsidian-Float-Search/assets/44117266/9ef8d3d9-ba5f-41e9-83d7-b93746066863">

### To Reproduce

1、打开Obsidian，调出Float-Search插件的悬浮窗口
2、点右上角设置，将“折叠搜索结果”、“显示上下文”、“说明搜索含义”打上勾
3、重启Obsidian
4、调出Float-Search插件的悬浮窗口发现设置全部被重置，需要重新打勾

### Obsidian Version

1.3.5

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by shuxueshuxue** [comment]
以及搜索结果的排序方式的设置.
总是重置到字典排序, 但有时按时间排序更有用些

**Comment by Quorafind** [comment]
修复。
