### ISSUE TITLE
Feature Request: Create new note

### ISSUE THREAD

**Issue by StefanoRausch** [Quorafind/Obsidian-Float-Search#33]
### Feature Requested

The `Float Search` plugin leverages the functionality of the core `Search` plugin, which is great.

However, if the file does not exist, one must open the core `Quick Switcher` plugin and paste the copied search term or type it again to create a new note.

Adding the ability to create a new file with `Cmd / Ctrl - Enter`, even if there is a content search result, i.e., no exact file name match, would simplify the workflow -- eliminating several additional steps. It would elevate the plugin to (nearly) the same level as `Omnisearch`, `Quick Switcher ++` and others, with a focus on efficient retrieval or creation of information without the feature bloat of comparable approaches.

In my opinion, it would make it even better than the peers. "DOTADIW" comes into my mind.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by StefanoRausch** [comment]
I would like to add `Shift Cmd / Ctrl - Enter` to create a new file in a new tab to the request.

**Comment by Quorafind** [comment]
Support ctrl+shift+enter in latest version
