### ISSUE TITLE
Feature Request: 保留搜索框字符。

### ISSUE THREAD

**Issue by thomasTAT** [Quorafind/Obsidian-Float-Search#39]
### Feature Requested

希望得到这样的效果
打开搜索框搜索，点进搜索结果。
再次打开搜索框，上次搜索的字符保留，并且被全选。
类似notion.

### Relevant Screenshot

![image](https://github.com/Quorafind/Obsidian-Float-Search/assets/109513632/02b02c61-d268-49b2-9b1b-3d15cdbf3dd3)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by xiahan4956** [comment]
赞同,希望增加这个功能

因为用到搜索,通常都是复杂的正则了,希望把上次结果保留

**Comment by Quorafind** [comment]
已经修复
