### ISSUE TITLE
Feature Request: New Hotkey Command: Switch Between Focus on Edit Mode and Focus on Search Modal

### ISSUE THREAD

**Issue by FelipeRearden** [Quorafind/Obsidian-Float-Search#4]
### Feature Requested

Hello @Quorafind !!!!

It's amazing that we can edit the note/file while we are in the **Preview** . Fantastic idea !!!!

The only thing that I miss is to be able to toggle between `Edit`  and `Search`

### My FR

This way this FR is about a new hotkey to toggle the Focus on `Search` and `Edit`

→ <kbd>TAB</kbd> Open Preview
→ <kbd>SHIFT+TAB</kbd> Close Preview
→ <kbd>New Hotkey</kbd> Focus on Edit Preview / Focus on Search Modal (Toggle)

This way, all workflows are covered :)

---

I hope you like my idea 🙏

Thanks for reading this !!!!

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Available in latest release, but it cannot be re-assigned. You can press CTRL+G to switch between.

**Comment by FelipeRearden** [comment]
> Available in latest release, but it cannot be re-assigned. You can press CTRL+G to switch between.

Thank you very much @Quorafind . From my tests, it's working perfect. 

🆘 **There is one specific thing for **Obsidian Mobile** that I would like to share with you** 

ℹ️ **This occurs on Obsidian Mobile on iPad using a keyboard and mouse** 

🐚 In a nutshell: on Obsidian Mobile, after hitting <kbd>CTRL+G</kbd> the Preview is NOT FOCUSED (Caret Cursors blinking) when the view is Live Preview which is my Obsidian Default View

## 📹 Let me show ... (I used a css snippet to go full screen 🤪 )

![video](https://user-images.githubusercontent.com/85180696/225988081-b5d493e0-b328-4d1a-a4bd-b4da04107e51.MOV)


1️⃣ TAB
2️⃣ CRTL + G

ℹ️ After hitting CRTL+G the caret cursors should appear since my default view is Live Preview 

ℹ️ I have to use the mouse and click on the Note Preview to focus on the Note

## How to solve this Issue for Mobile

This is the standard behavior for mobile, but there is a simple way to focus on the active note.

📸 For mobile we have this native command on Command Palette `Focus on Last Note`

![5FF2967C-67F5-482A-8E87-0A59DC2F6DB6](https://user-images.githubusercontent.com/85180696/225989247-a395c20d-053c-43c9-95eb-449b0f984e4f.jpeg)

This command focar the focus on Active Note which brings the Caret Cursor

## My Suggestion 

I you could add/insert/combine this native command to <kbd>CTRL+G</kbd> it will automatically bring the Caret Cursor when we focus on the Preview Note the same way we have on Desktop (I tested on Desktop before writing this tou you 😀)


--- 

Let me know if something is not clear and forgive for my poor english :)

Have a great day and thanks for this amazing new feature ☀️
