### ISSUE TITLE
[Bug]: Search Obsidian Globally (With Last State) no longer working after latest update (Version 3.4.5)

### ISSUE THREAD

**Issue by billy-bg** [Quorafind/Obsidian-Float-Search#40]
### Bug Description

The "Search Obsidian Globally (With Last State)" option is no longer working after the latest update, it will always show as empty.

### Obsidian Version

3.4.5

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Got fixed.
