### ISSUE TITLE
[Bug]: It is not compatible with hover editor, the search will be blocked by the suspended window, I hope the two can be compatible

### ISSUE THREAD

**Issue by jiajiala** [Quorafind/Obsidian-Float-Search#41]
### Bug Description

When using the hover editor, the search is obscured by the hover window, as shown in the figure
![image](https://github.com/Quorafind/Obsidian-Float-Search/assets/73203026/5d7b450d-5008-4484-b25c-a6b254d3bf4d)

Hopefully the two will be compatible

### Obsidian Version

3.4.5

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Can't do anything with my plugin. This is related to the hover editor plugin.
