### ISSUE TITLE
[Bug]: "Show More Context" not working in modal

### ISSUE THREAD

**Issue by azul372** [Quorafind/Obsidian-Float-Search#42]
### Bug Description

![image](https://github.com/Quorafind/Obsidian-Float-Search/assets/80684394/06fd588d-668b-4613-9586-3e6cf90fa7fd)

This button doesn't just work in the modal view. Once clicked, the window will be immediately closed instead of showing more context. It works fine with any other views though(split, window, tab)

### To Reproduce

1. launch "Search Obsidian Globally"
2. try to click the Show More Context

### Obsidian Version

1.4.16

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Got fixed
