### ISSUE TITLE
[Bug]: URI not working

### ISSUE THREAD

**Issue by freyana** [Quorafind/Obsidian-Float-Search#43]
### Bug Description

Hi, I'm using your Obsidian Floating Search Plugin on my Windows computer. Most parts work fine, thank you.

However, when I embed a URI command in an Obsidian page, it is not working properly. It opens the Floating Search but does not enter the query String. 

I have used the following URIs:
```
- [Search](obsidian://fs?query=Obsidian)
- [Search](obsidian://fs?vault=myVault&query=Obsidian)
```

The standard Search URI works:
`- [Search](obsidian://search?vault=myVault&query=Obsidian)`

Regards Freyana

### Relevant Screenshot

My URL:
![image](https://github.com/Quorafind/Obsidian-Float-Search/assets/8333812/505ef41a-4684-418b-ac2f-93bf2221dedc)

Search Result: 
![image](https://github.com/Quorafind/Obsidian-Float-Search/assets/8333812/7dae3298-c3f6-45b3-920b-690fcc9789b5)

### To Reproduce

1. Write URL `[Search](obsidian://fs?query=Obsidian)` on an Obsidian page
2. Click on the URL

### Obsidian Version

3.4.5

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Got fixed.
