### ISSUE TITLE
Feature Request: Some improvements to 【open search view (tab)】

### ISSUE THREAD

**Issue by calmwaves111** [Quorafind/Obsidian-Float-Search#44]
### Feature Requested

I have noticed that open search view (tab) cannot be closed by keyboard，which can only be closed by clicking twice with the mouse, as mentioned in issue 15 https://github.com/Quorafind/Obsidian-Float-Search/issues/15
So I won't close the search view (tab) anymore, I want to be able to quickly access this tab at any time. I set a shortcut key 'ctrl+shift+f' for the 【open search view (tab)】 command. When I first press this shortcut key, a search view (tab) is opened, but when I press' ctrl+shift+f 'again, it opens a new tab
I hope that when I use this command 'ctrl+shift+F' again after I have already opened a search view (tab), it will not open a new tab, but instead jump to an existing search view tab

### Relevant Screenshot

![image](https://github.com/Quorafind/Obsidian-Float-Search/assets/56907077/5ed20ab0-eec9-4161-a462-0d2b11e8dd03)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Done。
