### ISSUE TITLE
Feature Request: Save sort preferences

### ISSUE THREAD

**Issue by jamie9090** [Quorafind/Obsidian-Float-Search#45]
### Feature Requested

I would love to save the "sort by" - I would prefer "last modified" over A to Z, and I'm sure others would as well.

Love this plugin, finding it better thna Ominisearch for my needs :) 

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by cakechaser** [comment]
I also have the same request, would like to have "Collapse results" enabled by default, so it would be great to remember all sort options.

**Comment by Quorafind** [comment]
Got fixed

**Comment by cakechaser** [comment]
@Quorafind, the settings still don't save for me when I relaunch Obsidian.
They are saved only within the same working session.

Is is possible to keep this state between Obsidian re-launches?

**Comment by Quorafind** [comment]
When it reloads, it follows the settings from your default search view
