### ISSUE TITLE
[Bug]: 在锁定的页面使用浮动搜索，点击搜索结果后无法正常打开对应文件

### ISSUE THREAD

**Issue by ZouDongj** [Quorafind/Obsidian-Float-Search#46]
### Bug Description

在锁定的页面使用浮动搜索，点击搜索结果后无法正常打开对应文件，ctrl + enter也不行

### To Reproduce

锁定当前页面，然后使用插件进行搜索，点击搜索结果，预期在新标签页打开或其他方式打开，实际上无法正常打开

### Obsidian Version

1.5.3

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
已修复。
