### ISSUE TITLE
Feature Request: search result split with two tab

### ISSUE THREAD

**Issue by zhangchunyugithub** [Quorafind/Obsidian-Float-Search#48]
### Feature Requested

i find the search result view ,it`s not kindly when the notes is getting more and more；according to the person habbits,we always watch filename first, then watch the content in it  about search .some notes do it as i describe like evernote ，so, whether it can split result to two parts, one its the filename lists, and the other is relevant search content in the file。 

### Relevant Screenshot

current:
![image](https://github.com/Quorafind/Obsidian-Float-Search/assets/25131281/8180efc6-3ff0-452d-97f4-b7d0ce7e7305)
i think its better with below:
![image](https://github.com/Quorafind/Obsidian-Float-Search/assets/25131281/481f5dd7-5eba-4892-8afd-5c957d3c5f7f)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Not planned
