### ISSUE TITLE
Feature Request: Open search view (tab) do not respond to ctrl+w

### ISSUE THREAD

**Issue by calmwaves111** [Quorafind/Obsidian-Float-Search#49]
### Feature Requested

In the settings, I have disabled the Ctrl+w shortcut key (to close the current tab), but the opened serach view still corresponds to the Ctrl+w shortcut key closing the search view

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Fixed. Removed the default hotkey.
