### ISSUE TITLE
Feature Request: New Hotkey Command: Fold/Unfold Collapse Results

### ISSUE THREAD

**Issue by FelipeRearden** [Quorafind/Obsidian-Float-Search#5]
### Feature Requested

Hello @Quorafind !!!!

One more idea for enhance the keyboard navigation :)

My default view to open the float search with results Collapsed. 📸1️⃣

When I find the note that I am looking, then I open to see the results. 📸2️⃣  

This way, would be amazing if we could fold/unfold or open/close the `>` using a hotkey the same way that we have a hotkey to navigate from the matches `↑` `↓` with the arrow keys 

---

I hope you like my idea 🙏

Have a great day !!!!

### Relevant Screenshot

IMAGE 1️⃣

![E2995445-ECF1-4991-9991-182DB5D1EE3F](https://user-images.githubusercontent.com/85180696/225993865-256b6236-85df-4c5e-a8ff-d31e7865f14b.jpeg)

IMAGE 2️⃣

![83294431-A99A-4C21-911B-D16766BFBF4D](https://user-images.githubusercontent.com/85180696/225993941-e6e73624-e948-4a95-84f9-cd3d2b8a94ba.jpeg)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Available in latest release.

**Comment by FelipeRearden** [comment]
> Available in latest release.

Working perfect on Obsidian Mobile version 1.4.3 on iPadOS 16.2

Thank you very much @Quorafind !!!!!
