### ISSUE TITLE
Feature Request: automatically open search modal (or other specified view) for all search-invoking actions (e.g. clicking tags)

### ISSUE THREAD

**Issue by ko13** [Quorafind/Obsidian-Float-Search#51]
### Feature Requested

I really like the floating modal. 
It would be great, if clicking on a tag, which invokes obsidian search, would instead of opening the normal sidebar search, invoke the search in the modal (or maybe for other people's preferences in one of the other views, which could be defined in some plugin settings).
Also it would be nice to have a specific hotkey also for the floating modal (my workaround it so use previous state and then select the modal view once, but it is prone to be affected by changing the view).

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
+1.

In my case, I'd love this search view opening up when clicking on a property in the Property Core Plugin sidebar. (right now, this only happens when the floating search view in already open in a tab)

**Comment by Quorafind** [comment]
Supported.
