### ISSUE TITLE
[Bug]: “搜索设置”会重置

### ISSUE THREAD

**Issue by GeorgeBall** [Quorafind/Obsidian-Float-Search#52]
### Bug Description

搜索设置在设置过之后，再次打开会重置。

### Relevant Screenshot

![搜索设置](https://github.com/Quorafind/Obsidian-Float-Search/assets/22713391/2ec03620-1e63-4691-9853-39f67d103bbe)

### Obsidian Version

1.5.12

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Ci9Quester** [comment]
same problem

**Comment by Quorafind** [comment]
Fixed.
