### ISSUE TITLE
Feature Request: Navigate with `Ctrl-N`/`Ctrl-P` instead of arrow keys.

### ISSUE THREAD

**Issue by yaoyhu** [Quorafind/Obsidian-Float-Search#53]
### Feature Requested

Thanks for sharing such a wonderful plugin!

I think it would be better to use the `Ctrl-N`/`Ctrl-P`(or let it defined by users) instead of arrow keys to switch between search results when the cursor is focused on the search input box. 

I really love this plugin! Thanks again! 

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Supported in 4.0.0
