### ISSUE TITLE
[Bug]: An error occurred during startup

### ISSUE THREAD

**Issue by quanru** [Quorafind/Obsidian-Float-Search#54]
### Bug Description

![image](https://github.com/Quorafind/Obsidian-Float-Search/assets/11739753/f62ba6fe-a681-488d-903a-ee9493c8cc37)
![image](https://github.com/Quorafind/Obsidian-Float-Search/assets/11739753/f67a8974-c7cf-4fb5-b100-51cc6e2d0f0d)

### Obsidian Version

1.5.12

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Fixed.
