### ISSUE TITLE
[FR] 不同search view下的uri支持

### ISSUE THREAD

**Issue by Morganwan90** [Quorafind/Obsidian-Float-Search#56]
### Feature Requested

目前看到已经支持默认弹出窗口的uri，希望可以支持在tab里搜索的uri

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
以下为 4.0.0 支持

'tab' | 'split' | 'window' | ’sidebar‘

* obsidian://fs?query=hello&viewType=modal
* obsidian://fs?query=world&viewType=tab
* obsidian://fs?query=test (defaults to modal)
