### ISSUE TITLE
[Bug]: 鼠标点击不打开对应文件, 回车打开预览而不是新标签打开

### ISSUE THREAD

**Issue by DZL1943** [Quorafind/Obsidian-Float-Search#59]
### Bug Description

鼠标点击不打开对应文件, 回车打开预览而不是新标签打开.

应该是与其他插件有冲突.比如floating-toc、any-block.

### Obsidian Version

1.6.7

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
1. 鼠标点击打不开是插件冲突，请您劳烦排查
2. 新标签页打开是使用 Ctrl+Enter，具体可以看弹窗的下边的使用说明
