### ISSUE TITLE
Feature Request: edit mode as default preview mode

### ISSUE THREAD

**Issue by zcysxy** [Quorafind/Obsidian-Float-Search#6]
### Feature Requested

Thanks for this godsend plugin!

Currently, after pressing `Tab`, we can see the preview but cannot scroll it or edit without pressing another hotkey `Ctrl-G`. I wonder can there be a setting to set the default preview mode as edit mode? Then when we press `Tab`, we can directly edit the note content; when we press `Shift-Tab` or `Esc`, it takes the cursor back to the search box.
This behavior is also the default behavior of Blink feature of Make.md, which I think is more natural.

Or maybe we can change the hotkey `Ctrl-G` to a second `Tab`? Then the first tab opens the preview, the second tab enters the edit mode, and `Shift-Tab` or `Esc` takes it back to the search model.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Available in latest version. 
 
feat: support double tab to focus on file && Ctrl+Tab to focus back input

I don't want to influence the default Tab/Shift+Tab behavior in editor.

**Comment by zcysxy** [comment]
Thanks!
