### ISSUE TITLE
[Bug]: When cold starts to enter the Obsidian, and there is an error:

### ISSUE THREAD

**Issue by quanru** [Quorafind/Obsidian-Float-Search#61]
### Bug Description

When cold starts to enter the Obsidian, and there is an error:

![image](https://github.com/user-attachments/assets/88a7d6c9-7858-4268-bd68-164d726f87b6)

### Obsidian Version

1.7.4

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Fixed.
