### ISSUE TITLE
Feature Request: Drag and Drop Notes

### ISSUE THREAD

**Issue by Friedolito** [Quorafind/Obsidian-Float-Search#8]
### Feature Requested

Thank you for creating this plug-in! It's now my default in-file search and works great! 
I just wanted to drag and drop files from the search in to my note but this currently won't work. 
Maybe this (drag and drop results into a note and it will create an obsidian internal-link) could be a usefull feature to implement? It would help my workflow certainly.

Best Regards.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Supported.
